version: '3.8'

services:
  # Serviço do Banco de Dados MongoDB
  db:
    image: mongo:latest # Usa a imagem oficial do MongoDB
    container_name: mongo_db_reactgram
    ports:
      - "27017:27017" # Mapeia a porta do MongoDB para que você possa acessá-la de fora (ex: com MongoDB Compass)
    volumes:
      - mongodb_data:/data/db # Cria um volume para persistir os dados do banco
    environment:
      - MONGO_INITDB_ROOT_USERNAME=jason
      - MONGO_INITDB_ROOT_PASSWORD=ly61Ni8XOcwngaEv

  

volumes:
  mongodb_data: # Define o volume nomeado para persistência de dados